/* This file was generated by syncqt. */
#ifndef QT_QTGRPC_VERSION_H
#define QT_QTGRPC_VERSION_H

#define QTGRPC_VERSION_STR "6.5.3"

#define QTGRPC_VERSION 0x060503

#endif // QT_QTGRPC_VERSION_H
