/* This file was generated by syncqt. */
#ifndef QT_QTBODYMOVIN_VERSION_H
#define QT_QTBODYMOVIN_VERSION_H

#define QTBODYMOVIN_VERSION_STR "6.5.3"

#define QTBODYMOVIN_VERSION 0x060503

#endif // QT_QTBODYMOVIN_VERSION_H
