/* This file was generated by syncqt. */
#ifndef QT_QTAXBASE_VERSION_H
#define QT_QTAXBASE_VERSION_H

#define QTAXBASE_VERSION_STR "6.5.3"

#define QTAXBASE_VERSION 0x060503

#endif // QT_QTAXBASE_VERSION_H
