/* This file was generated by syncqt. */
#ifndef QT_QTHTTPSERVER_VERSION_H
#define QT_QTHTTPSERVER_VERSION_H

#define QTHTTPSERVER_VERSION_STR "6.5.3"

#define QTHTTPSERVER_VERSION 0x060503

#endif // QT_QTHTTPSERVER_VERSION_H
