/* This file was generated by syncqt. */
#ifndef QT_QTOPCUA_VERSION_H
#define QT_QTOPCUA_VERSION_H

#define QTOPCUA_VERSION_STR "6.5.3"

#define QTOPCUA_VERSION 0x060503

#endif // QT_QTOPCUA_VERSION_H
