/* This file was generated by syncqt. */
#ifndef QT_QTREPPARSER_VERSION_H
#define QT_QTREPPARSER_VERSION_H

#define QTREPPARSER_VERSION_STR "6.5.3"

#define QTREPPARSER_VERSION 0x060503

#endif // QT_QTREPPARSER_VERSION_H
