/* This file was generated by syncqt. */
#ifndef QT_QTAXSERVER_VERSION_H
#define QT_QTAXSERVER_VERSION_H

#define QTAXSERVER_VERSION_STR "6.5.3"

#define QTAXSERVER_VERSION 0x060503

#endif // QT_QTAXSERVER_VERSION_H
