/* This file was generated by syncqt. */
#ifndef QT_QTBLUETOOTH_VERSION_H
#define QT_QTBLUETOOTH_VERSION_H

#define QTBLUETOOTH_VERSION_STR "6.5.3"

#define QTBLUETOOTH_VERSION 0x060503

#endif // QT_QTBLUETOOTH_VERSION_H
