/* This file was generated by syncqt. */
#ifndef QT_QTSENSORS_VERSION_H
#define QT_QTSENSORS_VERSION_H

#define QTSENSORS_VERSION_STR "6.5.3"

#define QTSENSORS_VERSION 0x060503

#endif // QT_QTSENSORS_VERSION_H
