/* This file was generated by syncqt. */
#ifndef QT_QT3DCORE_VERSION_H
#define QT_QT3DCORE_VERSION_H

#define QT3DCORE_VERSION_STR "6.5.3"

#define QT3DCORE_VERSION 0x060503

#endif // QT_QT3DCORE_VERSION_H
