/* This file was generated by syncqt. */
#ifndef QT_QTCHARTSQML_VERSION_H
#define QT_QTCHARTSQML_VERSION_H

#define QTCHARTSQML_VERSION_STR "6.5.3"

#define QTCHARTSQML_VERSION 0x060503

#endif // QT_QTCHARTSQML_VERSION_H
