/* This file was generated by syncqt. */
#ifndef QT_QTCHARTS_VERSION_H
#define QT_QTCHARTS_VERSION_H

#define QTCHARTS_VERSION_STR "6.5.3"

#define QTCHARTS_VERSION 0x060503

#endif // QT_QTCHARTS_VERSION_H
