/* This file was generated by syncqt. */
#ifndef QT_QTHELP_VERSION_H
#define QT_QTHELP_VERSION_H

#define QTHELP_VERSION_STR "6.5.3"

#define QTHELP_VERSION 0x060503

#endif // QT_QTHELP_VERSION_H
