/* This file was generated by syncqt. */
#ifndef QT_QTACTIVEQT_VERSION_H
#define QT_QTACTIVEQT_VERSION_H

#define QTACTIVEQT_VERSION_STR "6.5.3"

#define QTACTIVEQT_VERSION 0x060503

#endif // QT_QTACTIVEQT_VERSION_H
